Name:           ros-melodic-openni2-launch
Version:        0.4.2
Release:        0%{?dist}
Summary:        ROS openni2_launch package

Group:          Development/Libraries
License:        BSD
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-melodic-depth-image-proc
Requires:       ros-melodic-image-proc
Requires:       ros-melodic-nodelet
Requires:       ros-melodic-openni2-camera
Requires:       ros-melodic-rgbd-launch
Requires:       ros-melodic-rospy
Requires:       ros-melodic-roswtf
Requires:       ros-melodic-tf
Requires:       usbutils
BuildRequires:  python-catkin_pkg
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-roslaunch

%description
Launch files to start the openni2_camera drivers using rgbd_launch.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Sat Dec 01 2018 Isaac I. Y. Saito <isaac.saito@plusonerobotics.com> - 0.4.2-0
- Autogenerated by Bloom

* Sat Oct 20 2018 Isaac I. Y. Saito <isaac.saito@plusonerobotics.com> - 0.4.1-0
- Autogenerated by Bloom

* Thu May 24 2018 Isaac I. Y. Saito <isaac.saito@plusonerobotics.com> - 0.3.0-0
- Autogenerated by Bloom

